### ISSUE TITLE
گرفتن لیست نمادهای قابل دریافت به طور خاص شاخص ها

### ISSUE THREAD

**Issue by sfmqrb** [alised/tse-index#5]
سلام 
میخواستم بدونم میشه از این لایبرری لیست شاخص ها رو گرفت 
اسمشون چون یه مقدار خاصه خوبه یه همچین قابلیتی داشته باشه که در یک درخواست بتونه لیست اسامی شاخص های قابل دریافت رو بگیریم

**Comment by sfmqrb-test** [comment]
به نظر پیاده شده
‍‍‍```
index.search("", "index").symbol
```

**Comment by alised** [comment]
سلام
داخل راهنما آمده است:
index.indices().symbol
